@startuml
'https://plantuml.com/class-diagram

class Client
hide Client members

Client *--> Document
Client *--> User
Client .> UserRole

class Document {
    + Document(currentUser : User)
    + publish() : void
    + returnDocAfterReview() : void
    + expire() : void
    + changeStateTo(state : State) : void
    + getCurrentUser() : User
    + changeUser(otherUser : User) : void
    + dividerBeforeChangingPublisher() : string
    + whoIsPublishingDocument() : string
    + getInitialState() : string
    + getTransitionDetails() : string

    - _currentUser : User
    - states : States
    - _currentState : State
    - _previousState : State
    - transition : Transition
}

Document --> State
Document *--> User
Document *--> Transition
Document ..> TransitionType
Document *--> States

enum StateType {
    INIT
    DRAFT
    MODERATION
    PUBLISHED
}

hide StateType methods

class States {
    + States(document : Document)
    + getInitialState() : State
    + getDraftState() : State
    + getModerationState() : State
    + getPublishedState() : State

    - _document : Document
    /'- _statesSingleton : States'/
    - map<StateType, State>  states
}

States --> StateType
States *--> State

/'States *--> InitialState
States *--> Draft
States *--> Moderation
States *--> Published'/

abstract class State {
    + State(document : Document)

    + publish() : void
    + returnDocAfterReview() : void
    + expire() : void

  - {abstract} publishImplementation() : void
  - {abstract} returnDocAfterReviewImplementation() : void
  - {abstract} expireImplementation() : void

  + getTransitionType() : TransitionType

  + {abstract} ~State()

  + ostream operator<<(\n\
  out : ostream,\n\
  state : State)

    # _document : Document
    - transitionType : TransitionType
}

State --> Document
State --> TransitionType
State ..> StateType

State <|-- InitialState
State <|-- Draft
State <|-- Moderation
State <|-- Published

class InitialState
hide InitialState members

class Draft
hide Draft members

class Moderation
hide Moderation members

class Published
hide Published members

class Transition {
    + Transition(\n\
  sourceState : State,\n\
  destinationState : State)

    + ostream operator<<(\n\
  out : ostream,\n\
  transition : Transition)

    - _sourceState : State
    - _destinationState : State
}

Transition -> State

enum TransitionType {
    NONE
    PUBLISH
    RETURN_DOC_AFTER_REVIEW
    EXPIRE
}

hide TransitionType methods

class User {
    + User(userRole : UserRole)
    + isAdmin() : bool

    + ostream operator<<(\n\
      out : ostream,\n\
      user : User)

    - _role : UserRole
}

User -> UserRole

enum UserRole {
    USER
    ADMIN
}

hide UserRole methods

@enduml
clear