@startuml
'https://plantuml.com/activity-diagram-beta

start
:User user;
:Document document(user);
:document.publish();
if (state == "draft") then (true)
    if (currentUser.role == "admin") then (true)
        :state = "published";
    else (false)
        :state = "moderation";
    endif
    stop
endif

if (state == "moderation") then (true)
    if (currentUser.role == "admin") then (true)
        :state = "published";
    else if (this->returnedFromReview) then (true)
        :state = "draft";
    endif
    stop
endif

if (state == "published") then (true)
    if (document.expired) then (true)
        :state = "draft";
    endif
endif

stop

@enduml
