@startuml
'https://plantuml.com/activity-diagram-beta

start
if (isNodeEmpty?) then
  stop
else
  :Initialize stack;
  :Push node to the stack;

  while (Are nodes present in the stack?) is (present)
    group Scan left subtree
    while (Has currently processed node left child?) is (yes)
      :Push the left child to the stack;
      :Move to the next left child node;
    end while
    end group

    group Process node on ""nodes"" stack
    :Save the top element of the stack;
    :Process the top element of the stack;
    :Pop - remove - the top element from the stack;
    end group

    group Scan right subtree
    if (Has currently removed node right child?) then (yes)
      :Push the right child of the removed node to the stack;
    else (no)
      'Duplicate code as opposed to the version with 'continue_goto'
      group Scan left subtree
      while (Has currently removed node left child?) is (yes)
        :Push the left child to the stack;
        :Move to the next left child node;
      end while
      endgroup

      group Process node on ""nodes"" stack
      :Get the top element of the stack;
      :Process the top element of the stack;
      :Pop the top element from the stack;
      end group

      group Process parent node
      :is root or parent node waiting for processing?\ni. e. is stack not empty?;
      if (Is root or parent node waiting for processing?)
        :Get the top element of the stack;
        :Process the top element of the stack;
        :Pop the top element from the stack;
      endif
      end group

      group Scan right subtree
      if (Has currently processed node right child?)
        :Push the right child to the stack;
      endif
      end group
    endif
    end group
  endwhile (empty)
stop

@enduml
