@startuml
'https://plantuml.com/class-diagram

class Client {
    + main() : int
}

Client *-> BinaryTree : owns

class BinaryTree {
    + begin() : BinaryTreeIteratorInOrder
    + end() : BinaryTreeIteratorInOrder
}

BinaryTree ..> BinaryTreeIteratorInOrder : returns
Client .> BinaryTreeIteratorInOrder : uses in for-each loops

class BinaryTreeIteratorInOrder

@enduml
