@startuml
'https://plantuml.com/activity-diagram-beta

start

:iterator = tree.begin();

repeat
    :get the element by dereferencing the iterator: *iterator;
    :go to next element: ++iterator;
repeat while (is at the end)

stop

@enduml
