@startuml
'https://plantuml.com/activity-diagram-beta

start
if (Is ""node"" empty?) then
    stop
else
    :Initialize ""nodes"" stack;
    :Initialize ""previous node"" as empty;

label outerLoop
while (Does ""node"" exist? OR Are nodes left in the stack?)
    if (Does ""node"" exist?)
        group pushing
        :Push ""node"" to the stack;
        :Set ""node"" to its left child;
        end group
    else
        group backtracking
        :Initialize ""current node"" to ""node"";
        if (Does right child of ""node"" exist? AND Does ""current node"" matches ""previous node""?)
            :Set ""node"" to the right child of ""current node"";
        else
            :Process ""current node"";
            :Set ""previous node"" to ""current node"";
            :Pop last node from the stack;
        end if
        end group
    end if
end while
stop
@enduml
