@startuml
'https://plantuml.com/sequence-diagram

main -> roundHole : RoundHole(5)

alt fitting roundPeg into roundHole
    main -> roundPeg : RoundPeg(5)
    main -> roundHole : fits(roundPeg)
    roundHole -> RoundCompatible : getRadius()
    RoundCompatible -> roundPeg : getRadius()
    roundPeg --> RoundCompatible : radius
    RoundCompatible --> roundHole : radius
    roundHole --> main : bool [true]
end

alt fitting small squarePeg into roundHole
    main -> squarePegSmall : SquarePeg(5)
    main -> squareToRoundPegAdapter : SquareToRoundPegAdapter(squarePegSmall)
    'squareToRoundPegAdapter -> RoundPeg : RoundPeg(0)

    main -> roundHole : fits(squareToRoundPegAdapter)
    roundHole -> RoundCompatible : getRadius()
    RoundCompatible -> squareToRoundPegAdapter : getRadius()
    squareToRoundPegAdapter -> squarePeg : getSideLength()
    squarePeg --> squareToRoundPegAdapter : sideLength
    squareToRoundPegAdapter --> RoundCompatible : radius
    RoundCompatible --> roundHole : radius
    roundHole --> main : bool [true]
end

alt fitting large squarePeg into roundHole
    main -> squarePegLarge : SquarePeg(10)
    main -> squareToRoundPegAdapter : plugToDifferentSquarePeg(squarePegLarge)

    main -> roundHole : fits(squareToRoundPegAdapter)
    roundHole -> RoundCompatible : getRadius()
    RoundCompatible -> squareToRoundPegAdapter : getRadius()
    squareToRoundPegAdapter -> squarePeg : getSideLength()
    squarePeg --> squareToRoundPegAdapter : sideLength
    squareToRoundPegAdapter --> RoundCompatible : radius
    RoundCompatible --> roundHole : radius
    roundHole --> main : bool [false]
end

@enduml
